### ISSUE TITLE
Allow cache option to be passed as a flag

### ISSUE THREAD

**Issue by bmoo** [d3sw/mold#100]
Caching is an option for mold that is useful for saving time during local development. But it is desirable for teams to have builds that don't use caching on the build server. Since the `.mold.yml` file is typically checked into source control and used by both build servers and local development, it would be helpful to have a flag, such as `--cache` to enable or disable caching. When set, this flag would override a `cache: false` setting in `.mold.yml`.

This would allow developers to take advantage of the caching feature without changing how the build server behaves.

**Comment by shuoyenl** [comment]
The cache option should be set per build instead of having a global switch to cache (or not cache) everything.
Closing the issue while there is already a -f flag which could be used to override the build config (with a customized local copy of .mold.yml for example) to achieve the same.

**Comment by bmoo** [comment]
Creating a whole extra file with identical contents, subject to configuration drift, in order to change a flag is a terrible alternative.
