### ISSUE TITLE
Isolate compute resources

### ISSUE THREAD

**Issue by bmoo** [d3sw/mold#101]
Mold currently provides network and disk isolation, but not compute isolation. Because mold builds are meant to be reproducible across many different computers, including build servers which may run many builds in parallel, its desirable to be able to further isolate builds.

Lack of isolation may often lead to confusion where a build may behave differently on a build server instance than on a developer’s laptop. A build would succeed on a developers laptop if it has plenty of resources available and then fail on a build server running many concurrent builds, and vice versa.

Having a place where compute is constrained would allow both developers and operations to observe and reproduce these failures in a predictable way. It would also allow operators to constrain concurrent build execution so that build servers are not overwhelmed.

Simple support for compute limits should include
- open files
- CPU
- memory

**Comment by euforia** [comment]
👍

**Comment by shuoyenl** [comment]
Support options as provided by docker: https://docs.docker.com/config/containers/resource_constraints/
