### ISSUE TITLE
Mold is throwing errors after update Docker to 17.12.0-ce on windows.

### ISSUE THREAD

**Issue by ktamayop** [d3sw/mold#112]
Steps to reproduce:

1. Update Docker to latest version on windows: 
![image](https://user-images.githubusercontent.com/8228671/34833045-3e90513c-f6cd-11e7-91d7-4da48bd6a0e6.png)

2. Run a mold build on any service. We're getting errors:

> mold

```
Name       : transformer-master-b5c7df89
Version    : 1.2.49-104-b5c7df8
Branch/Tag : master
Repo       :

Services   : 1
Builds     : 2
Artifacts  : 1

[configure/network/transformer-master-b5c7df89] Created a167635ff48cab7286f0762e1fdb3262db08e08743d414bd4842d58b6770f206
[setup/service/elasticsearch.transformer.auto0] Started docker.elastic.co/elasticsearch/elasticsearch:5.6.2
2018/01/11 12:40:34 ERR [Teardown] Error response from daemon: invalid name or ID supplied: ""
Error response from daemon: invalid name or ID supplied: ""
2018/01/11 12:40:34 Error response from daemon: invalid mount config for type "bind": bind source path does not exist
```

**Reproducibility:**
Reproduced on 3 out of 3 PCs with latest version of Docker for Windows - CE 17.12.0-ce.
Worked normally on one PC with previous version of Docker for Windows 17.0.1-ce.

**Comment by ktamayop** [comment]
Just one day after opening this issue, Docker has released a new version:

![image](https://user-images.githubusercontent.com/8228671/34891684-223dc774-f7b5-11e7-8d61-8b5122c3822b.png)

This new release `win47-(15139)` makes **mold** to work properly again. So probably this issue was related due to some problem with docker itself instead of mold.

I guess it'd be safe to close this issue.

**Comment by shuoyenl** [comment]
Verified mold v0.2.8 with docker 17.12.0-ce-win47 on windows 10 and cannot reproduce the issue.
Also verified mold v0.2.8 with docker 17.12.0-ce-mac49. 
According to ktamayop the issue happened on docker 17.12.0-ce-win46 but NOT on docker 17.12.0-ce-win47. It could be an issue of the previous release of docker or settings of the test itself while the error in the log in the original post says "bind source path does not exist".

**Comment by tmustain** [comment]
![image](https://user-images.githubusercontent.com/26314597/36356395-6e5c101c-14a6-11e8-951d-4887ca132f2d.png)

Am actually getting this error with latest mold on my laptop with docker 17.12.0-ce-win47 (15139).

[configure/network/sample-multitier-docker-master-7fc16b54] Created dea2d94ccef039650b1124e664bcf5ab6146552d54c8136b5c6ddbeedc14336c                                                                                              xist
2018/02/18 12:21:14 ERR [Teardown] Error response from daemon: invalid name or ID supplied: ""2018/02/18 12:21:14 Error response from daemon: invalid mount config for type "bind": bind source path does not exist
C:\Users\mustaint\Source\Repos\sample-multitier-docker>

**Comment by ktamayop** [comment]
@tmustain if you're still facing this I think I can share how I had solved this kind of issues before. It might be your case, also.

Please verify that you're exposing the docker daemon on your `tcp://localhost:2375`. See the below picture from my **Settings** > **General Tab**.
![image](https://user-images.githubusercontent.com/8228671/36379637-26392668-155e-11e8-81f1-c3d8d568c47e.png)
Also, please ensure you have shared the windows drive where your code is - according to the error you're seeing, that'll be `C:`. The following is again, from my docker settings (Shared Drives tab):
![image](https://user-images.githubusercontent.com/8228671/36379760-9798aaf4-155e-11e8-9b89-9b61135e0407.png)
One thing I've noticed though, is that if you happened to recently change you local windows password, you must reset the credentials you use in order to share the drive. My guess is that when Docker tries to grant you access to your Windows drive it's unable to do so, because the credentials are no longer valid. Resetting the credentials and clicking apply button will prompt you to enter your password back and the drive will be shared with the new credentials. This has solved this kind of errors for me.

Hope this helps!

**Comment by tmustain** [comment]
Thanks - bouncing the credentials did the trick. Much appreciated.
