### ISSUE TITLE
Use shorter build names in log.

### ISSUE THREAD

**Issue by euforia** [d3sw/mold#42]
`[build/mold-init-2e559262-0-1490843032336197087] ...`

The log line like the above needs to be shorter for better visual representation.

**Comment by KristinaEtc** [comment]
@euforia Under `shorter` you mean deleting a build time or changing it to human representation?

**Comment by shuoyenl** [comment]
Please keep the first 7 digits in the "prefix" and include the full container id (as a key/value pair) in the message.
