### ISSUE TITLE
Setup travis CI integration

### ISSUE THREAD

**Issue by euforia** [d3sw/mold#44]
- Setup .travis.yml for CI

**Comment by shuoyenl** [comment]
added travis.yml in branch travis. test is currently commented out while it assumes docker daemon being running on the build server.

**Comment by euforia** [comment]
@shuoyenl - take a look at this: https://github.com/d3sw/mold/blob/travis/.travis.yml

**Comment by euforia** [comment]
Here's the latest build.  Will need to troubleshoot: https://travis-ci.org/d3sw/mold/builds/268489522
