### ISSUE TITLE
Respect .dockerignore file

### ISSUE THREAD

**Issue by euforia** [d3sw/mold#50]
This is related to issue #12 as the ignore file is used when building context.

**Comment by djeikyb** [comment]
+1

**Comment by toddschilling** [comment]
@KristinaEtc what's the level of effort for this?

**Comment by euforia** [comment]
@djeikyb - Which part of it is making it difficult to run mold locally?  Reason I ask is we can then prioritize based on that.

**Comment by djeikyb** [comment]
Consider a directory that contains a git repo. There is a large file in this dir that is ignored by git and docker. It's needed for local development, but not the build process. Mold should also ignore this file. Instead mold spends a long time copying it into a mold container.

**Comment by djeikyb** [comment]
Workarounds are not satisfying. Dozens could be imagined, but really mold should be able to ignore files just like git and docker

**Comment by djeikyb** [comment]
For priority, I've moved on from the project where I first encountered this, but expect to encounter it fairly soon in the next project.
