### ISSUE TITLE
Add support for additional artifact repositories

### ISSUE THREAD

**Issue by toddschilling** [d3sw/mold#58]
Mold currently supports pushing docker images to an image repository.  We should also consider the following artifact targets.

- GitHub Release - for distributing release binaries
- NuGet Feed - for distributing dotnet packages
- S3 - for distributing static ui packages (Andrey and Konrad)

**Comment by euforia** [comment]
Mold operates only in the context of containers.  Pushing other artifacts is not in the scope of mold.

**Comment by toddschilling** [comment]
The way that I accomplish this for publishing nuget packages is to simply add the publish steps to the build steps in the nomad file.  I can provide an example if needed.
