### ISSUE TITLE
RC build for v0.2.6?

### ISSUE THREAD

**Issue by Igoreso** [d3sw/mold#68]
Hi. I'm new web developer at Deluxe and I'm using mold for my project.

I see that there is `cache` option being added. I could benefit from this option due to my slow internet connection. Can you please make an RC build for Windows for me? This would really help.

Thanks in advance,
Igor B

**Comment by euforia** [comment]
We're prepping the rc for 0.2.6.  In the mean time you should be able to clone master and build it.  Let me know if you have any issues.

**Comment by euforia** [comment]
There should be one up on the release page now.
