### ISSUE TITLE
Support reusable build images

### ISSUE THREAD

**Issue by toddschilling** [d3sw/mold#7]
We should find a clean way to allow complex build processes to define reusable build images which can be persisted to a repository.  The idea is to isolate the build process to only those things that change and to not have to recreate the entire build environment each time the build is executed.

We will need some consensus on the format of the .mold.yml file as well as how exactly the build process should work.

**Comment by euforia** [comment]
@bmoo - With the built caching feature would this still be needed?  I think the caching option should take care of your use case.

**Comment by bmoo** [comment]
@euforia Agreed. The behavior in #60 resolves my concerns.

**Comment by euforia** [comment]
Fixed by #60
