### ISSUE TITLE
Add a clean function to cleanup all build resources created

### ISSUE THREAD

**Issue by euforia** [d3sw/mold#71]
A function should be added to cleanup the create images, networks and other resources created to avoid build up.

**Comment by metroidprototype** [comment]
I think `cleanup` should be added as a bool field on the `build` config. There are times during local development where it's helpful to run a build through mold, and run the created image locally to test that the image mold build actually functions as intended.

**Comment by shuoyenl** [comment]
According to @metroidprototype, the original intent of the ticket is to completely clean up with an option to also remove all built images — including the build images, e.g. alpine, and the artifact images, e.g. atlas.
