### ISSUE TITLE
Latest stable Mold release (0.2.6) does not compile

### ISSUE THREAD

**Issue by bmoo** [d3sw/mold#75]
Here is the output

```
$ go build
# github.com/d3sw/mold
./docker_worker.go:166:29: cannot use exposedPorts (type map["github.com/docker/go-connections/nat".Port]struct {}) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortSet in assignment
./docker_worker.go:167:24: cannot use portBindings (type map["github.com/docker/go-connections/nat".Port][]"github.com/docker/go-connections/nat".PortBinding) as type "github.com/docker/docker/vendor/github.com/docker/go-connections/nat".PortMap in assignment
./gitversion.go:61:12: gt.head.IsTag undefined (type *plumbing.Reference has no field or method IsTag)
```

It seems that at some point the Docker folks changed their API so that exposedPorts is of type `nat.PortSet` instead of `map[nat.Port]struct{}`

This issue exists because Mold depends on the HEAD branch of its dependencies and so any API change to its dependencies will cause compile failures. This is fixed by pointing to specific versions of dependencies, either by vendoring them or using a tool that is capable of restoring specific versions.

**Comment by euforia** [comment]
It seems you are not using deps for dep. mgmt.  The following has been tested to be working:

- `make deps`
- `make mold`

Closing for now feel to open if you are still having issues
